name: Android User Build

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
                with:
                    submodules: 'true'
            -   name: set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 17
            -   name: Setting up the system environment
                run: cp ./.github/workflows/github-action-only.jks ./app/keys.jks
            -   name: Install NDK
                run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.1.8937393"
            -   name: Build with Gradle
                run: export KEYSTORE_PASS=000000000 && export ALIAS_NAME="key0" && export ALIAS_PASS=111111111 && export VERSION_CODE=1 && export VERSION_NAME="GITHUB-${GITHUB_SHA}" && ./gradlew app:copy_language_pack && ./gradlew assembleRelease
            -   name: Upload artifact
                uses: actions/upload-artifact@master
                with:
                    name: telegram-sms
                    path: app/build/outputs/apk/release/app-release.apk